name: deploy
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        
      - name: initialize hugo
        run: hugo new site .
        
      - name: pick hugo theme
        run: git init && git submodule add https://github.com/theNewDynamic/gohugo-theme-ananke themes/ananke && echo "theme = 'ananke'" >> config.toml
        
      - name: Debug Config
        run: config.toml
        
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          path: content

      - name: Build Link Index
        uses: jackyzha0/hugo-obsidian@v2.18
        with:
          input: content # input folder
          output: data   # output folder
          index: true    # whether to index content

      - name: Publish Site
        uses: chabad360/hugo-gh-pages@master
        with:
          githubToken: ${{ secrets.PERSONAL_TOKEN }}
