name: deploy
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          repository: muerwre/obsidian-publish
          
      - name: Debug
        run: |
          pwd
          ls -lah
          
      - name: Setup Yarn
        uses: mskelton/setup-yarn@v1.3.0

      - name: Git checkout
        uses: actions/checkout@v3
        with:
          path: content
          
      - name: Generate stuff
        run: yarn generate
        
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          folder: .output/public

#       - name: pick hugo theme
#         run: git init && git submodule add https://github.com/theNewDynamic/gohugo-theme-ananke themes/ananke
        
#       - name: Debug Config
#         run: |
#           echo "baseURL = 'https://notes.deiveris.lv/'" > config.toml
#           echo "languageCode = 'en-us'" >> config.toml
#           echo "title = 'notes'" >> config.toml
#           echo "theme = 'ananke'" >> config.toml
#           cat config.toml
        
#       - name: Git checkout
#         uses: actions/checkout@v3
#         with:
#           path: content

#       - name: Build Link Index
#         uses: jackyzha0/hugo-obsidian@v2.18
#         with:
#           input: content # input folder
#           output: data   # output folder
#           index: true    # whether to index content

#       - name: Publish Site
#         uses: chabad360/hugo-gh-pages@master
#         with:
#           githubToken: ${{ secrets.PERSONAL_TOKEN }}
