name: deploy
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          repository: jobindjohn/obsidian-publish-mkdocs

      - name: Git checkout
        uses: actions/checkout@v3
        with:
          path: docs
          
      - name: Deploy 🚀
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
